apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: kafkaconsumer-golang
  name: kafkaconsumer-golang
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: kafkaconsumer-golang
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: kafkaconsumer-golang
    spec:
      containers:
      - image: sebilhd/kafkaconsumer-golang:0.0.2
        imagePullPolicy: IfNotPresent 
        name: kafkaconsumer-golang
      restartPolicy: Always