apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: kafkaconsumer-dot-net-core
  name: kafkaconsumer-dot-net-core
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: kafkaconsumer-dot-net-core
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: kafkaconsumer-dot-net-core
    spec:
      containers:
      - image: kafkaconsumer-dot-net-core:0.0.1
        imagePullPolicy: IfNotPresent 
        name: kafkaconsumer-dot-net-core
      restartPolicy: Always