apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: kafkaconsumer-python
  name: kafkaconsumer-python
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: kafkaconsumer-python
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: kafkaconsumer-python
    spec:
      containers:
      - image: kafkaconsumer:0.0.14
        imagePullPolicy: IfNotPresent 
        name: kafkaconsumer-python
      restartPolicy: Always