name: build and push all

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Build all
        run: ./build-all.sh

      - name: Login Docker Hub
        run: ./docker-login-github.sh
        env:
          GITHUB_DOCKER_USERNAME: ${{ secrets.DOCKER_PASSWORD }}
          GITHUB_DOCKER_PASSWORD: ${{ secrets.DOCKER_USERNAME }}

      - name: Push all
        run: ./push-all.sh
